name: GeyserUpdater
main: org.geyserupdater.spigot.SpigotGeyserUpdaterPlugin
version: 1.0.3
api-version: 1.19
description: Auto-updater for GeyserMC and Floodgate
authors: [neha, Z3r0xh]
commands:
  geyserupdate:
    description: Execute Geyser/Floodgate update check or reload config
    usage: /geyserupdate [reload]
    permission: geyserupdater.admin
permissions:
  geyserupdater.admin:
    description: Can execute GeyserUpdater admin commands
    default: op
  geyserupdater.reload:
    description: Can reload GeyserUpdater configuration
    default: op
