name: GeyserUpdater
main: org.geyserupdater.spigot.SpigotGeyserUpdaterPlugin
version: 1.0.2
api-version: 1.19
description: Auto-updater for GeyserMC and Floodgate
authors: [neha, Z3r0xh]
commands:
  geyserupdate:
    description: Execute Geyser/Floodgate update check
    usage: /geyserupdate
    permission: geyserupdater.admin
permissions:
  geyserupdater.admin:
    description: Can execute GeyserUpdater admin commands
    default: op
