name: zPluginUpdater
main: org.pluginupdater.spigot.SpigotPluginUpdaterPlugin
version: 1.0.0
api-version: 1.19
load: STARTUP
description: Automatically downloads and updates plugins from official sources
authors: [neha, Z3r0xh]
softdepend: [Geyser-Spigot, floodgate, ProtocolLib, ViaVersion, ViaBackwards, ViaRewind]
commands:
  zpluginupdate-spigot:
    description: Execute plugin update check or reload config
    usage: /zpluginupdate-spigot [reload|check|packtest|webhooktest]
    permission: zpluginupdater.command
permissions:
  zpluginupdater.*:
    description: Grants all zPluginUpdater permissions
    default: op
    children:
      zpluginupdater.command: true
      zpluginupdater.command.update: true
      zpluginupdater.command.check: true
      zpluginupdater.command.reload: true
      zpluginupdater.command.packtest: true
      zpluginupdater.command.webhooktest: true
  zpluginupdater.command:
    description: Access to zPluginUpdater commands
    default: op
    children:
      zpluginupdater.command.update: true
      zpluginupdater.command.check: true
  zpluginupdater.command.update:
    description: Can trigger manual plugin updates
    default: op
  zpluginupdater.command.check:
    description: Can check plugin versions without updating
    default: op
  zpluginupdater.command.reload:
    description: Can reload zPluginUpdater configuration
    default: op
  zpluginupdater.command.packtest:
    description: Can simulate GeyserModelEngineExtension update for testing
    default: op
  zpluginupdater.command.webhooktest:
    description: Can test Discord webhook configuration
    default: op
