name: PluginUpdater
main: org.pluginupdater.spigot.SpigotPluginUpdaterPlugin
version: 1.0.0
api-version: 1.19
load: STARTUP
description: Auto-updater for Geyser, Floodgate and other plugins
authors: [neha, Z3r0xh]
commands:
  pluginupdate-spigot:
    description: Execute plugin update check or reload config
    usage: /pluginupdate-spigot [reload]
    permission: pluginupdater.admin
permissions:
  pluginupdater.admin:
    description: Can execute PluginUpdater admin commands
    default: op
  pluginupdater.reload:
    description: Can reload PluginUpdater configuration
    default: op
  pluginupdater.packtest:
    description: Can simulate GeyserModelEnginePackGenerator update for testing
    default: op
