name: PluginUpdater
main: org.pluginupdater.spigot.SpigotPluginUpdaterPlugin
version: 1.0.0
api-version: 1.19
load: STARTUP
description: Automatically downloads and updates plugins from official sources
authors: [neha, Z3r0xh]
softdepend: [Geyser-Spigot, floodgate, ProtocolLib, ViaVersion, ViaBackwards, ViaRewind]
commands:
  pluginupdate-spigot:
    description: Execute plugin update check or reload config
    usage: /pluginupdate-spigot [reload|check|packtest]
    permission: pluginupdater.command
permissions:
  pluginupdater.*:
    description: Grants all PluginUpdater permissions
    default: op
    children:
      pluginupdater.command: true
      pluginupdater.command.update: true
      pluginupdater.command.check: true
      pluginupdater.command.reload: true
      pluginupdater.command.packtest: true
  pluginupdater.command:
    description: Access to PluginUpdater commands
    default: op
    children:
      pluginupdater.command.update: true
      pluginupdater.command.check: true
  pluginupdater.command.update:
    description: Can trigger manual plugin updates
    default: op
  pluginupdater.command.check:
    description: Can check plugin versions without updating
    default: op
  pluginupdater.command.reload:
    description: Can reload PluginUpdater configuration
    default: op
  pluginupdater.command.packtest:
    description: Can simulate GeyserModelEngineExtension update for testing
    default: op
